# Generated by Django 4.2.1 on 2025-10-25 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название игры')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('platform', models.CharField(choices=[('PS3', 'PlayStation 3'), ('PS4', 'PlayStation 4'), ('PS5', 'PlayStation 5'), ('XBOX', 'XBOX'), ('PC', 'PC')], max_length=10, verbose_name='Платформа')),
                ('year_release', models.IntegerField(verbose_name='Год выпуска')),
                ('is_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('image', models.CharField(blank=True, max_length=255, verbose_name='Изображение')),
                ('age_rating', models.CharField(max_length=10, verbose_name='Возрастной рейтинг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('genres', models.CharField(max_length=255, verbose_name='Жанры')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['-time_create'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('rating', models.IntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], verbose_name='Рейтинг')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-date'],
            },
        ),
    ]
