# Generated by Django 4.2.1 on 2025-10-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
    ]
