# Generated by Django 4.2.1 on 2025-10-30 22:13

import django.core.validators
from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_uploadfiles_alter_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Оригинальное имя файла'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='file',
            field=models.FileField(upload_to=games.models.upload_files_unique_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'txt', 'zip', 'rar'])], verbose_name='Файл'),
        ),
    ]
