# Generated by Django 4.2.1 on 2025-11-05 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_uploadfiles_original_filename_alter_uploadfiles_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-time_create'], 'permissions': [('can_manage_promotions', 'Может управлять скидками и акциями'), ('can_export_data', 'Может экспортировать данные')], 'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
    ]
